#!/bin/zsh
set -e
set -o pipefail

main() {
  DOCKERFILES=( $(find -L . -iname '*Dockerfile' | sed 's|./||' | sort) )
  REPO="bassstring"

  for file in $DOCKERFILES; do
    IMG=$(echo $file | awk -F/ '{print $1}')
    BUILD_DIR="$IMG/"

    echo "Building ${REPO}/${IMG}:latest for context ${BUILD_DIR}"

    docker build --rm --force-rm -t "${REPO}/${IMG}:latest" "${BUILD_DIR}" || return 1

    echo "                       ---                                   "
    echo "Successfully built ${IMG}:latest with context ${BUILD_DIR}"
    echo "                       ---                                   "

    n=0
    until [ $n -ge 5 ]; do
      docker push "${REPO}/${IMG}:latest" && break
      echo "Try #$n failed... sleeping for 15 seconds"
      n=$((n+1))
      sleep 15
    done
  done
}

docker login
main
